name: TextUtility CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build and Test
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: '**/*.csproj'

      - name: Install PSResources
        run: ./build.ps1 -Bootstrap
        shell: pwsh

      - name: Build
        run: ./build.ps1 -Configuration Release
        shell: pwsh

      - name: Test
        run: ./build.ps1 -Test -NoBuild
        shell: pwsh

      - name: Test Windows PowerShell
        run: |
           ./build.ps1 -Bootstrap
           ./build.ps1 -Test -NoBuild
        if: matrix.os == 'windows-latest'
        shell: powershell

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: TextUtility-tests-${{ matrix.os }}
          path: testResults.xml
